### PR TITLE
Adapt new oemof structure

### LINKED ISSUE #112: New oemof structure has to be adapted
Omeof has a new structure.
Thus, importing oemof is deprectated. Instead, follwowing packages have to be installed (for smooth, using solph):
- oemof.network
- oemof.solph

Additionally, outputlib has moved into package oemof.solph

### PR DESCRIPTION
**Pull request by henhuy**
Fixes #112 

Todos:
- [x] Add oemof network and solph to requirements
- [x] Refactor outputlib imports to oemof.solph
- [ ] Import custom models

### CODE REVIEW

**Comment by henhuy** [comment]
Started to adapt new oemof structure. Not yet ready (draft!)

**Comment by j-brendel** [comment]
I added oemof.thermal to the requirements.txt

**Comment by j-brendel** [comment]
somehow component_var_battery got merged at 0e6ceda "merge dev", although it is not in dev

**Review by j-brendel — APPROVED** [review]
Time to update! :)

**Pull request merged**
